version: '3.7'

services:
  notification_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/notifications?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: cefalo
      SPRING_DATASOURCE_PASSWORD: cefalo_notifications

    networks:
      - notification_service


  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: notifications
      MYSQL_USER: cefalo
      MYSQL_PASSWORD: cefalo_notifications
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - db-data:/var/lib/mysql
    networks:
      - notification_service


volumes:
  db-data:
networks:
  notification_service:



