version: '3.7'

services:
  notification_service_mock:
    image: users-mysql
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/notifications?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:





